export function SubjectCategory(){
  const data = [
    {value:"ACTV", label: "Activities" },
    {value:"AGBS", label: "Agribusiness" },
    {value:"AGED", label: "Agriculture Education" },
    {value:"AGTC", label: "Agriculture Technology" },
    {value:"AGRO", label: "Agronomy" },
    {value:"AS", label: "Animal Science" },
    {value:"ANTH", label: "Anthropology" },
    {value:"APS", label: "Applied Plant Science" },
    {value:"ARAB", label: "Arabic" },
    {value:"ARCH", label: "Architecture" },
    {value:"ART", label: "Art" },
    {value:"AUTO", label: "Automotive" },
    {value:"BIO", label: "Biology" },
    {value:"ACCT", label: "Accounting" },
    {value:"BUS", label: "Business" },
    {value:"BA", label: "Business Analytics" },
    {value:"CHEM", label: "Chemistry" },
    {value:"CHLD", label: "Child Studies" },
    {value:"CHIN", label: "Chinese" },
    {value:"CE", label: "Civil Engineering" },
    {value:"COMM", label: "Communication" },
    {value:"CIT", label: "Computer Info Technology" },
    {value:"CS", label: "Computer Science" },
    {value:"CM", label: "Construction Management" },
    {value:"CYBR", label: "Cybersecurity" },
    {value:"DANC", label: "Dance" },
    {value:"DS", label: "Data Science" },
    {value:"ECD", label: "Early Child Development" },
    {value:"ECSE", label: "Early Child Special Ed" },
    {value:"ECON", label: "Economics" },
    {value:"ED", label: "Education" },
    {value:"ECEN", label: "Electrical/Computer Eng" },
    {value:"ENGT", label: "Engineering Technology" },
    {value:"ENG", label: "English" },
    {value:"ESL", label: "English Second Language" },
    {value:"EIL", label: "English as an Int'l Lang" },
    {value:"ESS", label: "Exercise/Sports Science" },
    {value:"FCS", label: "Family &amp; Consumer Sci" },
    {value:"FHGE", label: "Family History Research" },
    {value:"FAML", label: "Family Studies" },
    {value:"FIN", label: "Finance" },
    {value:"FS", label: "Food Science" },
    {value:"FAMF", label: "Foundations: American" },
    {value:"FR", label: "French" },
    {value:"GESC", label: "General Educ: Science" },
    {value:"GE", label: "General Education" },
    {value:"GS", label: "General Studies" },
    {value:"GIS", label: "Geographic Info Systems" },
    {value:"GEOG", label: "Geography" },
    {value:"GEOL", label: "Geology" },
    {value:"GER", label: "German" },
    {value:"GRK", label: "Greek" },
    {value:"HS", label: "Health Science" },
    {value:"HRHP", label: "Health, Rec, Human Pfrm" },
    {value:"HCA", label: "Healthcare" },
    {value:"HEB", label: "Hebrew" },
    {value:"HIST", label: "History" },
    {value:"HFED", label: "Home/Family Education" },
    {value:"HORT", label: "Horticulture" },
    {value:"HTM", label: "Hospitality/Tourism Mgmt" },
    {value:"HUM", label: "Humanities" },
    {value:"ITM", label: "Information Tech. Mgmt." },
    {value:"IDS", label: "Interdisciplinary Study" },
    {value:"ID", label: "Interior Design" },
    {value:"INTL", label: "International Studies" },
    {value:"LANG", label: "Language" },
    {value:"LATN", label: "Latin" },
    {value:"LR", label: "Library Research" },
    {value:"MGMT", label: "Management" },
    {value:"MET", label: "Manufacturing Eng Tech" },
    {value:"MKTG", label: "Marketing" },
    {value:"MATH", label: "Mathematics" },
    {value:"ME", label: "Mechanical Engineering" },
    {value:"MA", label: "Medical Assisting" },
    {value:"MS", label: "Military Science" },
    {value:"MUS", label: "Music" },
    {value:"NURS", label: "Nursing" },
    {value:"NRSF", label: "Nursing Family Skills" },
    {value:"NUTR", label: "Nutrition" },
    {value:"OSH", label: "Occ Safety and Health" },
    {value:"PARA", label: "Paramedicine" },
    {value:"PEAC", label: "Peace" },
    {value:"PHIL", label: "Philosophy" },
    {value:"PTA", label: "Physical Therapy Asst" },
    {value:"PH", label: "Physics" },
    {value:"PLSC", label: "Political Science" },
    {value:"PSYC", label: "Psychology" },
    {value:"PUBH", label: "Public Health" },
    {value:"RM", label: "Recreation Management" },
    {value:"REL", label: "Religion" },
    {value:"RUSS", label: "Russian" },
    {value:"SCED", label: "Science Education" },
    {value:"SMM", label: "Social Media Marketing" },
    {value:"SW", label: "Social Work" },
    {value:"SOC", label: "Sociology" },
    {value:"SPAN", label: "Spanish" },
    {value:"SPED", label: "Special Education" },
    {value:"TSOL", label: "Teach Eng Second Lang" },
    {value:"TA", label: "Theatre Arts" },
    {value:"WDD", label: "Web Design Development" },
    {value:"WELD", label: "Welding" },
  ]
  return data
}

